### ISSUE TITLE
wrong tag format about `v.`

### ISSUE THREAD

**Issue by maiha** [kostya/myhtml#4]
Hi kostya!
It seems latest tag name is not `v0.13` but `v.0.13`. Could you release `v0.13.1`? 🙏

**Comment by kostya** [comment]
pushd v0.14, somehow crystal deps not see v0.13.1

**Comment by maiha** [comment]
I can fetch `0.13.1` too. Thanks! 
```yaml
dependencies:
  myhtml:
    github: kostya/myhtml
    version: 0.13.1
```
